url: "http://honeydew-hawk.cloudvent.net"
url_master: "http://www.carefrance.org"
url_iraiser: "https://donner.carefrance.org"
name: CARE France - Signez une pétition
logo: /static/img/logo.png
encoding: UTF-8
woopra_id: carefrance.org
threads_id: LEFMVr
mode_dons:
  - bouton
  - equivalence
fire_base_url: https://care-petition.firebaseio.com/
blocs:
  - "1"
  - "2"
  - "3"
default_data:
    site_link: "http://www.carefrance.org"
    fb_link: "https://www.facebook.com/CARE.France"
    tw_link: "https://twitter.com/CAREfrance"
collections:
  posts:
    output: true
    permalink: "/posts/:title/"