url: "static"
url_master: ""
name: ADFINITAS Care Petition
logo: /static/img/logo.png
permalink: "/:title"
encoding: UTF-8
woopra_id: carefrance.org
email_test: "tech2@adfinitas.fr"
default_data:
  titre: "Integer a nibh fringilla, suscipit."
  introduction: "Etiam eget velit erat. Aenean diam sem, interdum a sapien id, hendrerit cursus est. Praesent cursus mi massa, nec finibus dolor volutpat euismod. In a eros vel lorem finibus semper. In hac habitasse platea dictumst. Morbi congue at risus non lobortis. Duis consectetur lobortis luctus. Vestibulum posuere magna vitae posuere euismod."
  button_sign: "Je signe la pétition"
  button_more: "En savoir +"
  form:
    introduction: "Praesent ullamcorper vel mauris at pretium. Fusce efficitur urna id enim ultrices lacinia. Cras quam enim, blandit in urna et, accumsan maximus libero. Nullam aliquam dui in ante pulvinar, sit amet ullamcorper est fermentum. Cras ullamcorper egestas sodales. Vivamus venenatis est in elementum feugiat. Maecenas porta mauris vestibulum, interdum turpis in, dictum nisi. Morbi porta erat vel pulvinar suscipit. Sed volutpat metus vehicula, suscipit nibh a, pharetra elit. Phasellus felis odio, viverra eu sodales a, porttitor sit amet diam."
    mandatory: "* champs obligatoires"
  content:
    titre: "Integer a nibh fringilla, suscipit."
    introduction: "Etiam eget velit erat. Aenean diam sem, interdum a sapien id, hendrerit cursus est. Praesent cursus mi massa, nec finibus dolor volutpat euismod. In a eros vel lorem finibus semper. In hac habitasse platea dictumst. Morbi congue at risus non lobortis. Duis consectetur lobortis luctus. Vestibulum posuere magna vitae posuere euismod."
  footer:
    titre: CARE SE MOBILISE
    introduction: "L’ONG CARE met les femmes au cœur de ses programmes et renforce leur autonomie en favorisant leur accès aux ressources, à l’éducation et à la santé."
    site_link: "http://www.carefrance.org/"
    fb_link: "https://www.facebook.com/CARE.France"
    tw_link: "https://twitter.com/CAREfrance"
    gp_link: ""
collections:
  petitions:
    output: true
    permalink: "/form/:title/"
  thanks:
    output: true
    permalink: "/thanks/:title/"
defaults:
  -
    scope:
      path: ""
      type: "thanks"
    values:
      layout: "merci"
  -
    scope:
      path: ""
      type: "petitions"
    values:
      layout: "petition"
